version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/seeds:/docker-entrypoint-initdb.d
