version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/seeds:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      # hydraとpepa-linha-darkが使えませんでした
      #   この２つはdesigns/*/adminer.cssが無かったです
      - ADMINER_DESIGN=pappu687
      # - ADMINER_DESIGN=pepa-linha # デザインは良いのですがウィンドウ幅からはみ出ていました
